AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  vpcCIDR:
    Description: CIDR notation for VPC
    Type: String

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpcCIDR
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
