AWSTemplateFormatVersion: 2010-09-09
Description: This Template creates VPC along with a Public Subnet

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the WordPress web server
    Type: AWS::EC2::KeyPair::KeyName
    Default: phoenixpair
  vpcCIDR:
    Default: 10.0.0.0/16
    Description: CIDR notation for VPC
    Type: String
  publicSubnet1CIDR:
    Default: 10.0.0.0/24
    Description: CIDR notation for Public Subnet 1
    Type: String
  AMI:
    Default: ami-013a129d325529d4d
    Description: AMI being used
    Type: String

Resources:
  phoenixVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpcCIDR
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: Phoenix VPC

  phoenixpublicSubnet1Name:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      VpcId: !Ref phoenixVPC
      CidrBlock: !Ref publicSubnet1CIDR
      Tags:
        - Key: Name
          Value: Phoenix Public Subnet

  phoenixigwName:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Phoenix IG
  phoenixAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref phoenixVPC
      InternetGatewayId: !Ref phoenixigwName
  phoenixEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: phoenixpair
      ImageId: !Ref AMI
      InstanceType: t3.micro
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - Ref: "phoenixsecGroupName"
          SubnetId: !Ref phoenixpublicSubnet1Name
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd

  phoenixsecGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows inbound access on TCP port 80 and allows unrestricted outbound access.
      VpcId: !Ref phoenixVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Phoenix Security Group
